name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.6

  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/app_icon.png"
  min_sdk_android: 21